name: Workflow

on:
  workflow_call:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.cached-deps.outputs.cache-primary-key }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup NodeJS
        uses: actions/setup-node@v6
        with:
          node-version: 24
          check-latest: true

      - name: Restore dependencies from cache
        uses: actions/cache/restore@v5
        id: cached-deps
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cached-deps.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile
      
      - name: Cache dependencies
        if: steps.cached-deps.outputs.cache-hit != 'true'
        uses: actions/cache/save@v5
        with:
          path: '**/node_modules'
          key: ${{ steps.cached-deps.outputs.cache-primary-key }}

  build:
    name: Linter checks
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Restore dependencies from cache
        uses: actions/cache/restore@v5
        with:
          path: '**/node_modules'
          key: ${{ needs.setup.outputs.cache-key }}

      - name: Run linter checks
        run: yarn lint
